### ISSUE TITLE
Remove numerator and denominator

### ISSUE THREAD

**Issue by jakubiec** [VirtusLab/ddd-public-materials#24]
It occurred that `numerator` and `denominator` are terms not familiar for musicians (confirmed with an expert). 

For `numerator` I propose to use `numberOfBeats`
For `denominator` I propose to use `noteValue` but [note value](https://en.wikipedia.org/wiki/Note_value) is more sophisticated concept. It might be hard to purely reflect it using Tiny-types later but indeed it could be a good exercise to develop another VO from scratch.

The other approach could be having `numberOfBeats` and `overNote` as fields.

Yet another way is to have class hierarchies like `FourOverFour`, `ThreeOverFour` etc. but it might be too complex to focus only on VO.

**Comment by pwojnowski** [comment]
IMHO class hierarchies won't work well, because in theory you can, basically, have any combination, like 17/24, etc.

**Comment by jakubiec** [comment]
we will go with `numberOfBeats` and `noteValue`

**Comment by jakubiec** [comment]
BTW. expert (my musician friend) completely doesn't care how this is named, he cares about the value as the whole
